version: '3'
services:
  node:
    build: ./node
    ports:
      - "3000:3000"
    volumes:
      - ./node:/usr/src/app
    networks:
      - fullcycle-desafio

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
    networks:
      - fullcycle-desafio

networks:
  fullcycle-desafio:
    driver: bridge
