version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=db
      - MYSQL_USER=djsilvajr
      - MYSQL_PASSWORD=123456
    ports:
      - "3306:3306"
    command: --innodb-use-native-aio=0
    container_name: db-fc
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - fullcycle-desafio

  node:
    build: ./node
    container_name: node-fc
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: ["npm", "start"]
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=djsilvajr
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=db
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - ./node:/usr/src/app
    networks:
      - fullcycle-desafio
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx-fc
    ports:
      - "8080:80"
    tty: true
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
    networks:
      - fullcycle-desafio

networks:
  fullcycle-desafio:
    driver: bridge
